timezone: "America/Los_Angeles"
title: UC Santa Cruz status
email: publicaffairs@ucsc.edu
description: >- # this means to ignore newlines until the next left-aligned key:
  UC Santa Cruz status page. You can also check for updates on Instagram.

social:
  twitter: https://twitter.com/ucsc
  facebook: https://www.facebook.com/ucsantacruz
  instagram: https://instagram.com/ucsc
  mastodon: https://mstdn.social/@ucsc

url: "https://status.ucsc.edu"
excerpt_separator: <!-- more -->

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
kramdown:
  parse_block_html: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections_dir: collections
collections:
  incidents:
    label: "incidents"
    output: true

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/ucsc-status.jpg
