title: UC Santa Cruz website status
email: pioweb@ucsc.edu
description: >- # this means to ignore newlines until "baseurl:"
  If you are seeing this page, the UC Santa Cruz website is down. Leave this page open and updates will appear here as they become available. You can also check for updates on our Twitter, Facebook, and Instagram accounts.

social:
  twitter: https://twitter.com/ucsc
  facebook: https://www.facebook.com/ucsantacruz
  instagram: https://instagram.com/ucsc

# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://status.ucsc.edu"


# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections_dir: _collections
collections:
  incidents:
    label: "incidents"
    output: true

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/ucsc-status.jpg
